Do_it_django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybo/urls.py 파일에 있는 url 매핑을 참고해서 처리하라는 의미
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # / 페이지에 해당하는 urlpatterns
]

Do_it_django/pybo/urls.py
from django.urls import path
from . import views

# 다른 앱이 프로젝트에 추가됐을 때, 같은 URL 별칭이 사용되는 걸 막기 위해 네임 스페이스를 저장한다.

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete,
         name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete,
         name='answer_delete'),
]

Do_it_django/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # User 모델은 django.contrib.auth 앱이 제공하는 모델이다.
                        # on_delete=models.CASCADE는 계정이 삭제되면 계정과 연결된 Question 모델 데이터를 모두 삭제하라는 의미다.
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True) # null=True : modify_date 칼럼에 null을 허용하겠다.
                                                # blank=True : form.is_valid()를 통한 입력 폼 데이터 검사 시 값이 없어도 된다.
    # 수정일시는 수정한 경우에만 생성되는 데이터이므로 null=True, blank=Ture를 지정해서 어떤 조건으로던 값을 비워둘 수 있다록 했다.

    def __str__(self):
        return self.subject
    # __str__ 메서드를 추가해서 장고 셸에서 Question.objects.all()을 해서 데이터 조회 시 id가 아닌 제목을 표시하게 한다.

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

Do_it_django/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

# 장고 폼은 2개의 폼으로 구분할 수 있다. froms.Form을 상속 받으면 폼.
# forms.ModelForm을 상속받으면 모델 폼이라 부른다.
# 모델 폼이란? 말 그대로 모델과 연결된 폼으로, 모델 폼 객체를 저장하면 연결된 모델의 데이터를 저장할 수 있다.

class QuestionForm(forms.ModelForm):
    class Meta: # 장고 모델 폼은 내부 클래스로 Meta 클래스를 반드시 가져야 한다.
        model = Question # 폼이 사용할 모델
        fields = ['subject', 'content'] # 필드들을 적어야 한다.
        labels = {
            'subject': '제목',
            'content': '내용',
        }
        # {{form.as_p}}는 디자인 측면에서 제한이 생긴다. 수작업으로 폼을 작성해보자
        # widget을 삭제했다.

# 답변 등록 기능에 장고 폼을 적용해보자.
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }

Do_it_django/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
def index(request):
    """
    pybo 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')
    # 1은 ?page=1과 같은 page 파라미터가 없는 url을 위해 기본값을 1로 지정한 것이다

    # 조회
    question_list = Question.objects.order_by('-create_date') # -create_date는 -기호로 작성일시의 역순을 의미한다.

    # 페이징 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여달라
    # Pageinator 클래스는 qeustion_list를 페이징 객체 paginator로 변환한다.
    # 두 번째 파라미터인 10은 페이지당 보여줄 게시물 개수를 의미한다.

    page_obj = paginator.get_page(page)
    # page_obj = paginator.get_page(page)로 만들어진
    # page_obj 객체에는 다음과 같은 속성들이 있다. 장고의 Paginatior 클래스를 이용하면 다른 속성들을 사용할 수 있어서 페이징 처리가 쉬워진다.
    # - pageinator.count 전체 게시물 개수
    # - paginator.per_page 페이지당 보여줄 게시물 개수
    # - number 현재 페이지 번호
    # - previous_page_number 이전 페이지 번호
    # - next_page_number 다음 페이지 번호
    # - has_previous 이전 페이지 유무
    # - has_next 다음 페이지 유무
    # - start_index 현재 페이지 시작 인덱스(1부터 시작)
    # - end_index 현재 페이지의 끝 인덱스(1부터 시작)

    context = {'question_list': page_obj} # 조회한 Question 모델 데이터를 context 변수에 저장했다. render 함수가 템플릿을 HTML로 변환하는 과정에서 사용되는 데이터다.
    # render 함수는 context에 있는 Question 모델 데이터 question_list 를 pybo/question_list.html 파일에 적용해 HTML 코드로 변환한다.
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("안녕하세요 pybo에 오신 것을 환영합니다.")

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # question = Question.objects.get(pk=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    # 질문 목록 화면에서 '질문 등록하기' 버튼을 누르면 get 방식으로 요청돼 질문 등록 화면이 나타나고,
    # 질문 등록 화면에서 입력값을 채우고 '저장하기' 버튼을 누르면 post 방식으로 요청돼 데이터가 저장된다.
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid(): # post 요청으로 받은 form이 유효한지 검사
            question = form.save(commit=False) # commit=Flase 는 임시저장을 한다는 뜻이다.
            # 폼에 현재 subject, content 필드만 있고 create_date 필드는 없으므로 임시저장 후
            # question 객체를 반환받아 create_date 에 값을 설정한 뒤 question.save()로 실제 저장한다.
            question.author = request.user # 추가한 속성 author 적용
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else: # request.method가 GET인 경우 호출
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user # 추가한 author 속성 적용
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문 수정
    """
    # 로그인 한 사용자(request.user)와 수정하려는 글쓴이(question.author)가 다르면 오류가 발생하도록 작성
    # messages 모듈 이용
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        # messages 모듈은 장고가 제공하는 기능으로, 오류를 임의로 발생시키려는 경우에도 사용된다. 폼 필드와 관련 없으므로 넌필드 오류에 해당됨.
        return redirect('pybo:detail', question_id=question.id)

    # 질문 수정 화면에서 '저장하기'를 누르면 /pybo/question/modify/2/ 페이지가 POST 방식으로 호출돼 데이터 수정이 이뤄진다.
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        # form = ... : question을 기본값으로 해서 화면으로 전달받은 입력값들을 덮어써서 QuestionForm을 생성하라는 의미
        # instance=question : instance 매개변수에 question을 지정하면 기존에 저장돼 있던 제목, 내용 값을 폼에 채울 수 있다.
        if form.is_valid():
            question = form.save(commit=False) # commit=False : 메모리상의 객체만 생성, DB에는 아직 저장 안됨.
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else: # 질문상세 화면에서 '수정'을 누르면 /pybo/question/modify/2/ 페이지가 GET 방식으로 호출돼 질문 수정 화면이 나타난다.
        form = QuestionForm(instance=question) # get 요청으로 기존 값 반영할 때는 request.post 빼고 저렇게만 작성하면 된다.
    context = {'form': form}
    # context : views에서 HTML 템플릿으로 데이터를 전달하는 택배상자 역할
    # 'form' : 템플릿에서 사용할 변수명
    # form : 실제 전달되는 데이터
    return render(request, 'pybo/question_form.html', context)
    # question_form.html 템플릿에 form이라는 이름으로 QuestionForm 객체를 전달한다는 의미

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

Do_it_django/templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-3">
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="content">답변내용</label>
                <textarea name="content" id="content" rows="10" class="form-control">
                    {{ form.content.value|default_if_none:'' }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

Do_it_django/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

{# 부트스트랩 card 컴포넌트 사용 #}
{# style 속성으로 white-space: pre-line으로 질문 내용, 답변 내용의 텍스트 줄바꿈 잘 보이게 함 #}
{# my-3은 상하 마진값 3을 의미하고, #}
{# py-2는 상하 패딩값 2, #}
{# p-2는 상하좌위 패딩값 2를 의미한다. #}
{# d-flex justify-content-end는 컴포넌트 오른쪽 정렬을 의미한다. #}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                {# 수정일시 표시하기 #}
                {% if question.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                    </div>
                {% endif %}
                {# 작성자와 작성일시 표시하기 #}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
        </div>
        {# 질문 수정 버튼 추가하기 #}
        {% if request.user == question.author %} {# 질문 수정버튼은 로그인한 사용자와 글쓴이가 같은 경우에만 보인다. #}
            <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                {# 삭제 버튼 #}
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                {# data-uri : 제이쿼리에서 ${this}. data('uri')와 같이 사용해서 그 값을 얻을 수 있는 속성 #}
                {# 삭제 함수가 실행되도록 class 속성에 delete 항목도 추가됐다. #}
            </div>
        {% endif %}
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                {# 답변 수정 일시 표시하기 #}
                {% if answer.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            {# 답변 수정 버튼 #}
            {% if request.user == answer.author %}
                <div class="my-3">
                    <a href="{% url 'pybo:answer_modify' answer.id %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                    {# 답변 삭제 버튼 #}
                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {# 답변 form #}
    <form action="{% url 'pybo:answer_create' question.id %}"
          method="post" class="my-3">
        {% csrf_token %} {# form 엘리먼트를 통해 전송된 데이터가 실제로 웹 브라우저에 작성된 데이터인지 판단하는 검사기 역할을 한다. #}
        <!-- 오류 표시 영역 시작 -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 영역 끝 -->
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %}disabled{% endif %} {# 로그인 상태가 아니면 답변 창 입력 불가 #}
                      class="form-control" rows="10"></textarea>
        </div>

        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
    {# $(document).ready(function() - 화면이 로드된 다음 자동으로 호출되는 제이쿼리 함수 #}
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

Do_it_django/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        <!-- 오류 표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 End -->

        <!--
        question_create 함수에서 form.is_vaild()가 실패했을 때 오류를 표시하기 위해 오류 표시 영역도 추가됐다.
        제목의 value에는 form.subject.value|default_if_none:''을 대입했는데, 오류 발생 시 기존 입력값을 유지하기 위함이다.
        default_if_none:''은 from.subject.value에 값이 없으면 'None'이라는 문자열이 표시되는데,
        이를 공백으로 표시하기 위해 사용된 템플릿 필터다.
        -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Do_it_django/templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            {# 항상 1로 시작하는 게시물 번호 문제 해결 - 템플릿 필터 만들어서 로드 후 일련번호 적용 #}
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-left">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
                {% if question.answer_set.count > 0 %} {# 질문에 달린 답변의 개수 표시하기 #}
                <span class="text-danger small ml-2">
                    {{ question.answer_set.count }}
                </span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a href="?page={{ question_list.previous_page_number }}" class="page-link">
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link" tabindex="-1">이전</a>
        </li>
        {% endif %}
    <!-- 페이지 리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %} {# 페이지 표시 제한 기능 구현 위해 한 줄 추가 #}
{#        |add:5 는 5씩 더해라 |add:-5는 5씩 빼라는 뜻 #}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a href="?page={{ page_number }}" class="page-link">
                {{ page_number }}
            </a>
        </li>
    {% else %}
        <li class="page-item">
            <a href="?page={{ page_number }}" class="page-link">
            {{ page_number }}
            </a>
        </li>
        {% endif %}
    {% endif %}
    {% endfor %}
    <!-- 다음 페이지 -->
    {% if question_list.has_next %}
        <li class="page-item">
            <a href="?page={{ question_list.next_page_number }}" class="page-link">
            다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link" tabindex="1" aria-disabled="true">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->

{#질문 등록 버튼을 만들어보자#}
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>

{% endblock %}