Do_it_django/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name= 'common/login.html' # common 디렉터리에 템플릿을 생성했다. regitration에서 common으로 변경한 것.
    ), name='login'),
    # django.contrib.auth 앱의 LoginView 클래스를 사용했으므로 별도의 views.py 파일 수정이 필요하지 않다.
    # LoginView 클래스는 registration이라는 템플릿 디렉터리에서 login.html 파일을 찾는다.
    # 하지만 우리는 로그인을 common 앱에 구현할 것이므로, registration 디렉터리에 템플릿 파일을 생성하기 보다는,
    # common 디렉터리에 템플릿을 생성하는 것이 좋다.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

Do_it_django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybo/urls.py 파일에 있는 url 매핑을 참고해서 처리하라는 의미
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # / 페이지에 해당하는 urlpatterns
]

Do_it_django/pybo/urls.py
from django.urls import path
from . import views

# 다른 앱이 프로젝트에 추가됐을 때, 같은 URL 별칭이 사용되는 걸 막기 위해 네임 스페이스를 저장한다.

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete,
         name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete,
         name='answer_delete'),
]

Do_it_django/templates/base.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- include 기능으로 내비게이션 영역을 분리했다 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

Do_it_django/templates/form_errors.html
{# 필드 오류 : 입력값이 누락됐거나 형식에 맞지 않음 #}
{# 넌필드 오류 : 입력값과 관계없이 발생한 오류 #}

{% if form.errors %} {# form에 에러가 있는지 확인하는 조건문 #}
    {% for field in form %} {# form의 field를 순회. 여기서 field는 이름, 비밀번호 같은 각각의 폼 필드를 의미한다. #}
        {% for error in field.errors %} <!--필드 오류를 출력한다 --> {# 각 필드에 여러 오류가 있을 수 있으므로 순회 #}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong> {# 필드의 라벨명 #}
                {{ error }} {# 실제 에러 메시지 #}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류 출력 -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

Do_it_django/templates/navbar.html
<!-- 내비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a href="{% url 'pybo:index' %}" class="navbar-brand">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
    data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            {# 현재 로그인 상태를 판별해 로그인 상태라면 로그아웃 링크를, 로그아웃 상태면 로그인 링크를 보여준다. #}
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'common:logout' %}">
                    {% csrf_token %}
                    <button class="nav-link" type="submit" style="border: none; background: none; outline: none;">
                        {{ user.username }} (로그아웃)
                    </button>
                    </form>
                {% else %}
                <a href="{% url 'common:login' %}" class="nav-link">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>