Do_it_django/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name= 'common/login.html' # common 디렉터리에 템플릿을 생성했다. regitration에서 common으로 변경한 것.
    ), name='login'),
    # django.contrib.auth 앱의 LoginView 클래스를 사용했으므로 별도의 views.py 파일 수정이 필요하지 않다.
    # LoginView 클래스는 registration이라는 템플릿 디렉터리에서 login.html 파일을 찾는다.
    # 하지만 우리는 로그인을 common 앱에 구현할 것이므로, registration 디렉터리에 템플릿 파일을 생성하기 보다는,
    # common 디렉터리에 템플릿을 생성하는 것이 좋다.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

Do_it_django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybo/urls.py 파일에 있는 url 매핑을 참고해서 처리하라는 의미
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # / 페이지에 해당하는 urlpatterns
]

Do_it_django/pybo/urls.py
from django.urls import path
from . import views

# 다른 앱이 프로젝트에 추가됐을 때, 같은 URL 별칭이 사용되는 걸 막기 위해 네임 스페이스를 저장한다.

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete,
         name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete,
         name='answer_delete'),
]

Do_it_django/common/models.py
from django.db import models

# Create your models here.

Do_it_django/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# django.contrib.auth.forms 패키지의 UserCreationForm 클래스 상속
# UserCreationForm은 기본적으로 가지고 있는 username, password1, password2 속성에 부가 정보인 email속성을 추가하기 위해
# UserCreationForm을 상속한 UserForm을 만든 것.

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email")

Do_it_django/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm

# Create your views here.
def signup(request):
    """
    회원가입
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid(): # UserCreationForm의 is_valid 함수는 회원가입 화면의 필드값 3개가 모두 입력됐는지,
        # 비밀번호1과 비밀번호2가 같은지, 비밀번호의 값이 비밀번호 생성 규칙에 맞는지 등을 검사한다.
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

# signup 함수는 POST 요청인 경우 화면에서 입력한 데이터로 새로운 사용자를 생성하고,
# GET 요청인 경우 common/signup.html 화면을 반환한다.

# form.cleaned_data.get은 회원가입 화면에서 입력한 값을 안전하게 가져오기 위해 사용하는 메서드다.
# form.cleaned_data - Django 폼에서 유효성 검사를 통과한 데이터들을 담고 있는 딕셔너리
# .get() - 파이썬 딕셔너리의 기본 메서드 (안전하게 값을 가져오는 방법)

# 그리고 회원가입이 완료된 이후 자동으로 로그인되도록 authenticate 함수와 login 함수를 사용했다.

### login(request, user) 함수가 하는 일 // django.contrib.auth에서 제공하는 login 함수를 import해서 사용
# 1. 세션에 사용자 정보 저장 - 브라우저의 세션에 로그인된 사용자 정보를 기록
# 2. 쿠키 설정 - 브라우저에 세션 ID를 담은 쿠키를 설정
# 3. request.user 업데이트 - 이후 요청에서 request.user로 현재 로그인된 사용자에 접근 가능
# Django가 이런 복잡한 로그인 처리를 모두 내부적으로 해주기 때문에, 우리는 단순히 login(request, user)만 호출하면 된다.

Do_it_django/templates/common/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
        <div class="row">
            <div class="col-4">
                <h4>로그인</h4>
            </div>
            <div class="col-8 text-right">
                <span>
                    계정이 없으신가요? <a href="{% url 'common:signup' %}">회원가입 하기</a>
                </span>
            </div>
        </div>
        <form method="post" action="{% url 'common:login' %}" class="post-form">
            {% csrf_token %}
            <!-- 로그인 성공 후 이동되는 URL -->
            <input type="hidden" name="next" value="{{ next }}"> {# 로그인 후 next 파라미터의 URL로 이동하게 함 #}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="username">사용자 ID</label>
                <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
                {# django에서 |는 템플릿의 필터 연산자다. 앞의 값을 뒤의 필터로 처리한다는 의미 #}
                {# form : view에서 전달받은 폼 객체 #}
                {# username : 폼의 username 필드 #}
                {# value : 해당 필드의 현재 값 #}
                {# default_if_none: Django의 내장 템플릿 필터 #}
                {# :'' 필터의 매개변수 (빈 문자열) #}
            </div>
            <div class="form-group">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
{% endblock %}

Do_it_django/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
        <div class="row my-3">
            <div class="col-4">
                <h4>회원가입</h4>
            </div>
            <div class="col-8 text-right">
                <span>계정이 있으신가요? <a href="{% url 'common:login' %}">로그인 하기</a></span>
            </div>
        </div>
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="username">사용자 이름</label>
                    <input type="text" class="form-control" id="username" name="username"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" id="password1" name="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" id="password2" name="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">생성하기</button>
        </form>
    </div>
{% endblock %}